export const data = [
    // {
    //     id: 'auth_type',
    //     name: 'auth_type',
    //     type: 'text',
    //     stream: ['Twitter', 'Youtube', 'Facebook', 'Linkedin'],
    //     header: 'credentials',
    //     label: 'Authentication Type',
    //     required: true,
    //     readOnly: true,
    //     initial: {
    //         Twitter: 'auth2',
    //         Youtube: 'api_key',
    //         Facebook: 'api_key',
    //         Linkedin: 'auth2',
    //     },
    // },
    {
        id: 'api_key',
        name: 'api_key',
        type: 'text',
        stream: ['Youtube', 'Facebook', 'Instagram', 'Twitter'],
        header: 'credentials',
        label: 'API Key',
        required: true,
        readOnly: false,
        initial: {
            Twitter: '',
            Linkedin: '',
            Youtube: '',
            Facebook: '',
            Zoho: '',
        },
    },

    {
        id: 'channel_id',
        name: 'channel_id',
        type: 'text',
        stream: ['Youtube', 'Facebook'],
        header: 'credentials',
        label: 'Channel ID',
        required: true,
        readOnly: false,
        initial: {
            Twitter: '',
            Linkedin: '',
            Youtube: '',
            Facebook: '',
            Zoho: '',
        },
    },
    // {
    //     id: 'base_url',
    //     name: 'base_url',
    //     type: 'text',
    //     stream: ['Twitter', 'Youtube', 'Facebook', 'Linkedin'],
    //     header: 'credentials',
    //     label: 'Base URL',
    //     required: true,
    //     readOnly: true,
    //     initial: {
    //         Twitter: 'https://api.twitter.com/2/',
    //         Youtube: 'https://www.googleapis.com/youtube/v3/',
    //         Facebook: 'https://graph.facebook.com/v3.2/',
    //         Linkedin: 'https://api.linkedin.com/v2/',
    //     },
    // },
    // {
    //     id: 'access_token',
    //     name: 'access_token',
    //     type: 'text',
    //     stream: ['Twitter'],
    //     header: 'credentials',
    //     label: 'Access Token',
    //     required: true,
    //     readOnly: false,
    //     initial: {
    //         Twitter: '',
    //         Linkedin: '',
    //         Youtube: '',
    //         Facebook: '',
    //         Zoho: '',
    //     },
    // },
    // // {
    //   id: "refresh_token",
    //   name: "refresh_token",
    //   type: "text",
    //   stream: [],
    //   header: "parameters",
    //   label: "Refresh Token",
    //   required: true,
    //   readOnly: true,
    //   initial: {
    //     Zoho: "",
    //     Twitter: "",
    //     Linkedin: "",
    //     Youtube: "",
    //     Facebook: "",
    //   },
    // },
    // {
    //   id: "client_id",
    //   name: "client_id",
    //   type: "text",
    //   stream: [],
    //   header: "parameters",
    //   label: "Client ID",
    //   required: true,
    //   readOnly: false,
    //   initial: {
    //     Zoho: "",
    //     Twitter: "",
    //     Youtube: "",
    //     Facebook: "",
    //     Linkedin: "",
    //   },
    //   placeholder: "1000.Z4OWM6BIKRB67BECMWF9WZYFXUB8HE",
    // },
    // {
    //   id: "client_secret",
    //   name: "client_secret",
    //   type: "text",
    //   stream: [],
    //   header: "parameters",
    //   label: "Client Secret",
    //   required: true,
    //   readOnly: false,
    //   initial: {
    //     Zoho: "",
    //     Twitter: "",
    //     Youtube: "",
    //     Facebook: "",
    //     Linkedin: "",
    //   },
    //   placeholder: "d902f2f611e61fbaea7dbf32522aa2ed48e4f78cc5",
    // },
    // {
    //   id: "grant_type",
    //   name: "grant_type",
    //   type: "text",
    //   stream: [],
    //   header: "parameters",
    //   label: "Grant Type",
    //   required: true,
    //   readOnly: true,
    //   initial: {
    //     Zoho: "",
    //     Twitter: "",
    //     Youtube: "",
    //     Facebook: "",
    //     Linkedin: "",
    //   },
    //   placeholder: "refresh_token",
    // },

    // {
    //     id: 'path_name',
    //     name: 'path_name',
    //     type: 'text',
    //     stream: ['Twitter', 'Youtube', 'Facebook', 'Linkedin'],
    //     header: 'path',
    //     label: 'Path Name',
    //     required: true,
    //     readOnly: true,
    //     initial: {
    //         Zoho: 'socialmedia/zoho_{file}_records.json',
    //         Twitter: 'socialmedia/twitter_{file}_records.json',
    //         Youtube: 'socialmedia/youtube_{file}_records.json',
    //         Facebook: 'socialmedia/facebook_{file}_records.json',
    //         Linkedin: 'socialmedia/linkedin_{file}_records.json',
    //     },
    // },

    {
        id: 'endpoint',
        type: 'select',
        name: 'endpoint',
        stream: [
            'Youtube',
            'Linkedin',
            'Twitter',
            'Facebook',
            'Spotify',
            'Tiktok',
        ],
        header: 'Endpoint',
        label: 'Endpoint',
        required: true,
        placeholder: '',
        initial: {
            Twitter: '',
            Linkedin: '',
            Youtube: '',
            Facebook: '',
            Zoho: '',
        },
    },
    {
        id: 'history',
        name: 'history',
        type: 'checkbox',
        stream: ['Youtube'],
        header: 'Endpoint',
        label: 'Duration Of Data to Populate ',
        required: true,
        readOnly: false,
        initial: {
            Twitter: '',
            Linkedin: '',
            Youtube: '',
            Facebook: '',
            Zoho: '',
        },
    },
    {
    id: "competitors",
    name: "competitors",
    type: "text",
    stream: ["Youtube"],
    header: "credentials",
    label: "Know Your Competitors (max 3 separated by semicolon)",
    required: false,
    placeholder: "https://www.youtube.com/@AgilisiumConsulting",
    readOnly: false,
    initial: {
      Twitter: "",
      Linkedin: "",
      Youtube: "",
      Facebook: "",
      Zoho: "",
    },
  },
];
export const adminmenu = ['Dashboard', 'Config', 'User'];
export const viewermenu = ['Dashboard'];
